version: "3.9"

services:
  web-server:
    image: parvez0/portfolio:v2.0.3
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ssl-cert:/etc/nginx/ssl

volumes:
  ssl-cert: